# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'WeatherMobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherMobile
  pod 'Alamofire'

  target 'WeatherMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherMobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
